sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 43.142.121.125
    port: 3306
    database: sky
    username: sky
    password: sky
  qiniu:
    # 在七牛云的账号中获取
    access-key: I59Xckq-KTqN6k58Y4yjaP7e6dQcQVWabGOJclVr
    secret-key: rB8VlGMHETazBYpvh6XXKtL5FWnFXde1auZ_P1kp
    bucket-name: clueli
    base-url: http://img.clueli.top/
  redis:
    host: 43.142.121.125
    port: 6379
    password: sky
    database: 0